### ISSUE TITLE
There is no reason glass types should not support blocks that have Tile Entities

### ISSUE THREAD

**Issue by tterrag1098** [Ephys/TinkersSteelworks#55]
I see nothing in your code that would break if a block has a TE, so restricting additions to the list seems pointless. It prevents things like warded glass and EIO fused quartz from working.

**Comment by Ephys** [comment]
That's because I don't like the way deep tanks are implemented and it might be prone to changes

Right now the controller is checking the structure one block at a time every now and then, that's not very efficient and is also very slow to detect structure changes when the tank is huge.

I was thinking of replacing every glass by a tile entity, but it also doesn't please me. But just in case I don't want to break existing tanks which is why tile entities are blacklisted

What I could also do is list every tank controller and when a block is broken, check if it's part of a tank. I believe that would be the best way to do it but I need to check if it would actually work. If it does I'll whitelist tile entities
